//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MojaProdaja.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proizvod
    {
        public int Id { get; set; }
        public string Naziv { get; set; }
        public string Slika { get; set; }
        public Nullable<int> Cijena { get; set; }
        public string DetaljanOpis { get; set; }
        public Nullable<int> KategorijaId { get; set; }
        public Nullable<int> KorisnikId { get; set; }
    
        public virtual Kategorija Kategorija { get; set; }
        public virtual Korisnik Korisnik { get; set; }
    }
}
